// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhcdIloHoRdfCrynbjOYUU78Ha37B40ME',
    appId: '1:521870006732:web:5a759a37ea5bdb28b0e569',
    messagingSenderId: '521870006732',
    projectId: 'petcare-34b13',
    authDomain: 'petcare-34b13.firebaseapp.com',
    storageBucket: 'petcare-34b13.firebasestorage.app',
    measurementId: 'G-09FQ1KMV2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjGNUrm2iUfQQ67pSXyZ_Z_SDNnOA2ktQ',
    appId: '1:521870006732:android:84152393163c3cabb0e569',
    messagingSenderId: '521870006732',
    projectId: 'petcare-34b13',
    storageBucket: 'petcare-34b13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7yu0dCbkMV2pPESRn9Ku92mzwe0yxss4',
    appId: '1:521870006732:ios:42e95b3e94878f58b0e569',
    messagingSenderId: '521870006732',
    projectId: 'petcare-34b13',
    storageBucket: 'petcare-34b13.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7yu0dCbkMV2pPESRn9Ku92mzwe0yxss4',
    appId: '1:521870006732:ios:42e95b3e94878f58b0e569',
    messagingSenderId: '521870006732',
    projectId: 'petcare-34b13',
    storageBucket: 'petcare-34b13.firebasestorage.app',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhcdIloHoRdfCrynbjOYUU78Ha37B40ME',
    appId: '1:521870006732:web:f346dcb2dee1bf7db0e569',
    messagingSenderId: '521870006732',
    projectId: 'petcare-34b13',
    authDomain: 'petcare-34b13.firebaseapp.com',
    storageBucket: 'petcare-34b13.firebasestorage.app',
    measurementId: 'G-S7M85KDRQL',
  );
}
